name: Publish Analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
        version: "latest"
    
    - name: Set up Python
      run: uv python install 3.13
    
    - name: Install dependencies
      run: uv sync
    
    - name: Run data analysis
      run: |
        uv run jupyter nbconvert --to notebook --execute notebooks/*.ipynb
        uv run jupyter nbconvert --to html notebooks/*.ipynb
    
    - name: Upload analysis artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analysis-results
        path: |
          notebooks/*.html
          data/processed/
